# Created by `python forgi/threedee/utilities/modified_res.py 165D.pdb 1A9N.pdb 1AV6.pdb 1B23.pdb 1B2M.pdb 1B7F.pdb 1BMV.pdb 1BR3.pdb 1C9S.pdb 1CSL.pdb 1CVJ.pdb 1CWP.pdb 1D4R.pdb 1DDL.pdb 1DFU.pdb 1DI2.pdb 1DQF.pdb 1DQH.pdb 1DUH.pdb 1DUQ.pdb 1E7K.pdb 1E8O.pdb 1E8S.pdb 1EC6.pdb 1EFO.pdb 1EFW.pdb 1EGK.pdb 1ET4.pdb 1F1T.pdb 1F27.pdb 1F7V.pdb 1F7Y.pdb 1F8V.pdb 1FEU.pdb 1FIR.pdb 1FIX.pdb 1FJG.pdb 1FUF.pdb 1FXL.pdb 1G1X.pdb 1G2E.pdb 1G2J.pdb 1GTF.pdb 1GTN.pdb 1H2C.pdb 1H38.pdb 1H3E.pdb 1H4S.pdb 1HMH.pdb 1HYS.pdb 1I5L.pdb 1I6H.pdb 1I6U.pdb 1I9X.pdb 1IBL.pdb 1IL2.pdb 1IVS.pdb 1J1U.pdb 1J2B.pdb 1J6S.pdb 1J8G.pdb 1J9H.pdb 1JBR.pdb 1JID.pdb 1JZV.pdb 1K8W.pdb 1KD4.pdb 1KD5.pdb 1KFO.pdb 1KH6.pdb 1KNZ.pdb 1KOG.pdb 1KQ2.pdb 1KXK.pdb 1L3Z.pdb 1LNT.pdb 1M5K.pdb 1M8V.pdb 1M8W.pdb 1M8X.pdb 1M8Y.pdb 1MDG.pdb 1MHK.pdb 1MJI.pdb 1MMS.pdb 1MSW.pdb 1MZP.pdb 1N1H.pdb 1N32.pdb 1N33.pdb 1N35.pdb 1N38.pdb 1NBS.pdb 1NJP.pdb 1NTB.pdb 1NUJ.pdb 1NYI.pdb 1O9M.pdb 1OOA.pdb 1P6V.pdb 1P79.pdb 1PGL.pdb 1PJO.pdb 1PVO.pdb 1Q2R.pdb 1Q93.pdb 1QA6.pdb 1QBP.pdb 1QC0.pdb 1QCU.pdb 1QF6.pdb 1QLN.pdb 1QRS.pdb 1QU2.pdb 1QVF.pdb 1R3E.pdb 1R9F.pdb 1RLG.pdb 1RNA.pdb 1RPU.pdb 1S03.pdb 1S72.pdb 1S76.pdb 1S77.pdb 1SA9.pdb 1SAQ.pdb 1SDR.pdb 1SDS.pdb 1SER.pdb 1SI3.pdb 1T0D.pdb 1T0E.pdb 1T0K.pdb 1TFW.pdb 1TFY.pdb 1U0B.pdb 1U1Y.pdb 1U63.pdb 1U6B.pdb 1U9S.pdb 1UN6.pdb 1URN.pdb 1UTD.pdb 1UVI.pdb 1UVJ.pdb 1UVL.pdb 1UVM.pdb 1UVN.pdb 1VBY.pdb 1VQ6.pdb 1VQL.pdb 1VQM.pdb 1VQN.pdb 1VQO.pdb 1WMQ.pdb 1WNE.pdb 1WPU.pdb 1WZ2.pdb 1X8W.pdb 1XJR.pdb 1XNQ.pdb 1XNR.pdb 1XOK.pdb 1XPE.pdb 1XPU.pdb 1Y0Q.pdb 1Y1Y.pdb 1Y26.pdb 1Y27.pdb 1YFG.pdb 1YKV.pdb 1YTU.pdb 1YVP.pdb 1YYK.pdb 1YYW.pdb 1YZ9.pdb 1YZD.pdb 1Z7F.pdb 1ZBH.pdb 1ZBI.pdb 1ZDJ.pdb 1ZDK.pdb 1ZH5.pdb 1ZHO.pdb 1ZX7.pdb 205D.pdb 255D.pdb 259D.pdb 280D.pdb 283D.pdb 2A04.pdb 2A43.pdb 2A64.pdb 2A8V.pdb 2AKE.pdb 2ANR.pdb 2AO5.pdb 2ASB.pdb 2ATW.pdb 2AWE.pdb 2AZ2.pdb 2AZX.pdb 2B3J.pdb 2B63.pdb 2BBV.pdb 2BGG.pdb 2BH2.pdb 2BTE.pdb 2BX2.pdb 2C0B.pdb 2C4R.pdb 2CT8.pdb 2CV1.pdb 2CZJ.pdb 2D6F.pdb 2DB3.pdb 2DER.pdb 2DLC.pdb 2DR8.pdb 2DU3.pdb 2E9R.pdb 2E9T.pdb 2E9Z.pdb 2EC0.pdb 2EZ6.pdb 2F4S.pdb 2F4V.pdb 2F8K.pdb 2F8S.pdb 2F8T.pdb 2FQN.pdb 2FZ2.pdb 2G3S.pdb 2G4B.pdb 2G91.pdb 2G92.pdb 2GCS.pdb 2GDI.pdb 2GJE.pdb 2GJW.pdb 2GRB.pdb 2GTT.pdb 2GUN.pdb 2GXB.pdb 2HT1.pdb 2HVY.pdb 2I82.pdb 2I91.pdb 2IL9.pdb 2IX1.pdb 2IZN.pdb 2J0S.pdb 2JA6.pdb 2JA7.pdb 2JA8.pdb 2JEA.pdb 2JLT.pdb 2JLV.pdb 2JLW.pdb 2NR0.pdb 2NUE.pdb 2NUG.pdb 2NVQ.pdb 2NVT.pdb 2NZ4.pdb 2O3V.pdb 2O5I.pdb 2OE5.pdb 2OE8.pdb 2OIU.pdb 2OIY.pdb 2OZB.pdb 2P7E.pdb 2PJP.pdb 2PN4.pdb 2PO1.pdb 2PXV.pdb 2PY9.pdb 2Q1O.pdb 2Q1R.pdb 2Q66.pdb 2QK9.pdb 2QKB.pdb 2QUS.pdb 2QUW.pdb 2QUX.pdb 2QWY.pdb 2R20.pdb 2R7S.pdb 2R7T.pdb 2R7U.pdb 2R7V.pdb 2R7W.pdb 2R7Z.pdb 2R92.pdb 2R93.pdb 2RFK.pdb 2TMV.pdb 2UUA.pdb 2UWM.pdb 2UXB.pdb 2UXC.pdb 2UXD.pdb 2V6W.pdb 2V7R.pdb 2VAL.pdb 2VNU.pdb 2VOD.pdb 2VON.pdb 2VOO.pdb 2VOP.pdb 2VPL.pdb 2VQE.pdb 2VRT.pdb 2VUM.pdb 2VUQ.pdb 2W2H.pdb 2W89.pdb 2WJ8.pdb 2X1F.pdb 2XB2.pdb 2XBM.pdb 2XD0.pdb 2XGJ.pdb 2XNR.pdb 2XS2.pdb 2XS5.pdb 2XS7.pdb 2XSL.pdb 2XXA.pdb 2XZL.pdb 2XZO.pdb 2Y8W.pdb 2Y8Y.pdb 2Y9H.pdb 2YJY.pdb 2ZI0.pdb 2ZKO.pdb 2ZNI.pdb 2ZUE.pdb 2ZY6.pdb 2ZZM.pdb 2ZZN.pdb 333D.pdb 353D.pdb 354D.pdb 361D.pdb 364D.pdb 377D.pdb 387D.pdb 397D.pdb 398D.pdb 3A2K.pdb 3A3A.pdb 3A6P.pdb 3ADD.pdb 3ADI.pdb 3ADL.pdb 3AEV.pdb 3AGV.pdb 3AHU.pdb 3AM1.pdb 3AMU.pdb 3AVT.pdb 3AVU.pdb 3AVV.pdb 3AVW.pdb 3AVX.pdb 3AVY.pdb 3B0U.pdb 3B31.pdb 3B5S.pdb 3BNN.pdb 3BNS.pdb 3BNT.pdb 3BOY.pdb 3BSB.pdb 3BSO.pdb 3BSU.pdb 3BSX.pdb 3BT7.pdb 3BX2.pdb 3BX3.pdb 3CGP.pdb 3CGR.pdb 3CGS.pdb 3CIY.pdb 3CJZ.pdb 3CR1.pdb 3CUL.pdb 3CZ3.pdb 3CZW.pdb 3D0M.pdb 3D0U.pdb 3D2S.pdb 3D2V.pdb 3DD2.pdb 3DHS.pdb 3DIR.pdb 3E2E.pdb 3E5C.pdb 3EGZ.pdb 3EPK.pdb 3EQT.pdb 3ERC.pdb 3F2Q.pdb 3F4H.pdb 3FHT.pdb 3FS0.pdb 3FTE.pdb 3FTF.pdb 3FTM.pdb 3FU2.pdb 3G0H.pdb 3G9Y.pdb 3GIB.pdb 3GLP.pdb 3GM7.pdb 3GPQ.pdb 3GS5.pdb 3GTG.pdb 3GTJ.pdb 3GTL.pdb 3GTO.pdb 3GTP.pdb 3GTQ.pdb 3GVN.pdb 3GX5.pdb 3H3V.pdb 3HAX.pdb 3HGA.pdb 3HHN.pdb 3HJF.pdb 3HJY.pdb 3HK2.pdb 3HO1.pdb 3HOU.pdb 3HOV.pdb 3HOW.pdb 3HOY.pdb 3HOZ.pdb 3HSB.pdb 3HTX.pdb 3I2S.pdb 3I4M.pdb 3I4N.pdb 3I5X.pdb 3IAB.pdb 3IBK.pdb 3ICE.pdb 3ICQ.pdb 3IEV.pdb 3IVK.pdb 3IVN.pdb 3IWN.pdb 3J06.pdb 3J7A.pdb 3J7Y.pdb 3JAM.pdb 3JB7.pdb 3JB9.pdb 3JXR.pdb 3K0J.pdb 3K49.pdb 3K4E.pdb 3K5Q.pdb 3K5Y.pdb 3K5Z.pdb 3K61.pdb 3K62.pdb 3K64.pdb 3KFU.pdb 3KMQ.pdb 3KMS.pdb 3KNC.pdb 3KOA.pdb 3KS8.pdb 3KTW.pdb 3L25.pdb 3LA5.pdb 3LOA.pdb 3LOB.pdb 3LRR.pdb 3LWR.pdb 3M3Y.pdb 3M4O.pdb 3M7N.pdb 3MDG.pdb 3MDI.pdb 3MEI.pdb 3MIJ.pdb 3MJ0.pdb 3MOJ.pdb 3MQK.pdb 3NCU.pdb 3ND3.pdb 3ND4.pdb 3NDB.pdb 3NJ6.pdb 3NKB.pdb 3NL0.pdb 3NMA.pdb 3NMR.pdb 3NMU.pdb 3NNA.pdb 3NNC.pdb 3NNH.pdb 3NPN.pdb 3NVI.pdb 3NVK.pdb 3O7V.pdb 3OG8.pdb 3OIN.pdb 3OK4.pdb 3OL9.pdb 3OVA.pdb 3OX0.pdb 3P22.pdb 3P49.pdb 3P4C.pdb 3P4D.pdb 3P59.pdb 3P6Y.pdb 3PDR.pdb 3PEY.pdb 3PF4.pdb 3PKM.pdb 3PLA.pdb 3PO2.pdb 3PO3.pdb 3PTX.pdb 3PU0.pdb 3PU1.pdb 3Q0L.pdb 3Q0N.pdb 3Q0P.pdb 3Q0Q.pdb 3Q0R.pdb 3Q0S.pdb 3Q1Q.pdb 3Q2T.pdb 3Q3Z.pdb 3Q50.pdb 3QGC.pdb 3QJJ.pdb 3QJL.pdb 3QJP.pdb 3QRP.pdb 3QRR.pdb 3QSU.pdb 3R1C.pdb 3R1D.pdb 3R1E.pdb 3R2C.pdb 3R2D.pdb 3R4F.pdb 3R9W.pdb 3R9X.pdb 3RC8.pdb 3RER.pdb 3RG5.pdb 3RKF.pdb 3RTJ.pdb 3RW6.pdb 3RZO.pdb 3S14.pdb 3S15.pdb 3S16.pdb 3S17.pdb 3S1M.pdb 3S1N.pdb 3S1R.pdb 3S2D.pdb 3S2H.pdb 3S49.pdb 3SIU.pdb 3SIV.pdb 3SJ2.pdb 3SKI.pdb 3SKL.pdb 3SN2.pdb 3SNP.pdb 3SQW.pdb 3SSF.pdb 3SUX.pdb 3SYW.pdb 3SZX.pdb 3T1Y.pdb 3T3O.pdb 3T4B.pdb 3T5N.pdb 3T5Q.pdb 3TD0.pdb 3TD1.pdb 3TRZ.pdb 3TS0.pdb 3TS2.pdb 3TUP.pdb 3TZR.pdb 3UCZ.pdb 3ULD.pdb 3UZT.pdb 3V6Y.pdb 3V71.pdb 3V74.pdb 3V7E.pdb 3VJR.pdb 3VNV.pdb 3VYX.pdb 3W3S.pdb 3WBM.pdb 3WC2.pdb 3WFS.pdb 3WQY.pdb 3WZI.pdb 3X1L.pdb 3ZC0.pdb 3ZP8.pdb 402D.pdb 404D.pdb 406D.pdb 409D.pdb 413D.pdb 420D.pdb 421D.pdb 422D.pdb 433D.pdb 435D.pdb 437D.pdb 438D.pdb 439D.pdb 466D.pdb 472D.pdb 4A2X.pdb 4A36.pdb 4A3B.pdb 4A3D.pdb 4A3E.pdb 4A3G.pdb 4A3L.pdb 4A93.pdb 4AFY.pdb 4AL6.pdb 4AL7.pdb 4AM3.pdb 4ANG.pdb 4AOB.pdb 4AQ7.pdb 4ATO.pdb 4AY2.pdb 4B3G.pdb 4B3O.pdb 4B3T.pdb 4BA2.pdb 4BBS.pdb 4BOC.pdb 4BW0.pdb 4BWM.pdb 4BXX.pdb 4BY7.pdb 4C4W.pdb 4C7O.pdb 4C8Y.pdb 4C8Z.pdb 4C9D.pdb 4CS1.pdb 4CSF.pdb 4D25.pdb 4DB2.pdb 4DR6.pdb 4DR7.pdb 4DWA.pdb 4DZS.pdb 4E58.pdb 4E59.pdb 4E5C.pdb 4E6B.pdb 4E78.pdb 4ED5.pdb 4ENB.pdb 4ERD.pdb 4EYA.pdb 4F02.pdb 4F1N.pdb 4F3T.pdb 4FE5.pdb 4FRG.pdb 4FRN.pdb 4FSJ.pdb 4FTB.pdb 4FTS.pdb 4FVU.pdb 4FWT.pdb 4FXD.pdb 4G0A.pdb 4G7O.pdb 4G9Z.pdb 4GCW.pdb 4GG4.pdb 4GHA.pdb 4GHL.pdb 4GKJ.pdb 4GKK.pdb 4GL2.pdb 4GMA.pdb 4GV3.pdb 4GXY.pdb 4GZY.pdb 4H5O.pdb 4H5P.pdb 4H8K.pdb 4HKQ.pdb 4HOR.pdb 4HOS.pdb 4HOT.pdb 4HT9.pdb 4I67.pdb 4IFD.pdb 4IG8.pdb 4II9.pdb 4IJS.pdb 4ILL.pdb 4ILM.pdb 4IOA.pdb 4IQS.pdb 4J39.pdb 4J7L.pdb 4J7M.pdb 4JAB.pdb 4JAH.pdb 4JF2.pdb 4JGN.pdb 4JIY.pdb 4JNG.pdb 4JNX.pdb 4JRC.pdb 4JRD.pdb 4JRT.pdb 4JV5.pdb 4JVH.pdb 4JVY.pdb 4JXZ.pdb 4JYA.pdb 4JZU.pdb 4K0K.pdb 4K27.pdb 4K31.pdb 4K4S.pdb 4K4U.pdb 4K4V.pdb 4K4Y.pdb 4K4Z.pdb 4K50.pdb 4KHP.pdb 4KJI.pdb 4KNQ.pdb 4KQ0.pdb 4KQY.pdb 4KR6.pdb 4KR7.pdb 4KRE.pdb 4KRF.pdb 4KTG.pdb 4KXT.pdb 4KYY.pdb 4KZ2.pdb 4KZD.pdb 4L81.pdb 4L8H.pdb 4LCK.pdb 4LGT.pdb 4LJ0.pdb 4LMZ.pdb 4LVZ.pdb 4LX6.pdb 4M4O.pdb 4M59.pdb 4M6D.pdb 4M7A.pdb 4M7D.pdb 4MCF.pdb 4MDX.pdb 4MGN.pdb 4MSR.pdb 4N2Q.pdb 4N2S.pdb 4N48.pdb 4NFQ.pdb 4NGC.pdb 4NGD.pdb 4NGF.pdb 4NGG.pdb 4NH3.pdb 4NH5.pdb 4NH6.pdb 4NHA.pdb 4NKU.pdb 4O26.pdb 4O41.pdb 4O8J.pdb 4OAV.pdb 4OHY.pdb 4OHZ.pdb 4OJI.pdb 4OL8.pdb 4OLA.pdb 4OO1.pdb 4OO8.pdb 4OOG.pdb 4OQ9.pdb 4P3T.pdb 4P3U.pdb 4P43.pdb 4P5J.pdb 4P8Z.pdb 4P97.pdb 4P9R.pdb 4PCJ.pdb 4PCO.pdb 4PDB.pdb 4PEH.pdb 4PEI.pdb 4PHY.pdb 4PJO.pdb 4PKD.pdb 4PLX.pdb 4PMI.pdb 4PMW.pdb 4PQU.pdb 4PQV.pdb 4PR6.pdb 4PWD.pdb 4PY5.pdb 4Q0B.pdb 4Q5S.pdb 4Q5V.pdb 4QEI.pdb 4QI2.pdb 4QIK.pdb 4QIL.pdb 4QJD.pdb 4QJH.pdb 4QK8.pdb 4QK9.pdb 4QLM.pdb 4QM6.pdb 4QOZ.pdb 4QPX.pdb 4QQB.pdb 4QU6.pdb 4QU7.pdb 4QVC.pdb 4QVD.pdb 4QVI.pdb 4QYZ.pdb 4R0D.pdb 4R3I.pdb 4R4V.pdb 4RBY.pdb 4RBZ.pdb 4RC0.pdb 4RCJ.pdb 4RDX.pdb 4RGE.pdb 4RJ1.pdb 4RMO.pdb 4RUM.pdb 4RZD.pdb 4S2X.pdb 4S3N.pdb 4TS0.pdb 4TU0.pdb 4TUX.pdb 4TYW.pdb 4TYY.pdb 4TZ0.pdb 4TZ6.pdb 4TZZ.pdb 4U34.pdb 4U35.pdb 4U3L.pdb 4U6K.pdb 4U7U.pdb 4U8T.pdb 4UY8.pdb 4UYK.pdb 4V19.pdb 4V2S.pdb 4W5N.pdb 4W92.pdb 4WAN.pdb 4WFA.pdb 4WFL.pdb 4WJ3.pdb 4WJ4.pdb 4WKR.pdb 4WRT.pdb 4WSB.pdb 4WTC.pdb 4WTD.pdb 4WTE.pdb 4WTF.pdb 4WTI.pdb 4WTJ.pdb 4WTK.pdb 4WTL.pdb 4WTM.pdb 4WZM.pdb 4WZQ.pdb 4X2B.pdb 4X4O.pdb 4X4U.pdb 4X4V.pdb 4X6A.pdb 4X9E.pdb 4XBF.pdb 4XJN.pdb 4XK0.pdb 4XLN.pdb 4XW0.pdb 4XW1.pdb 4XWF.pdb 4XWW.pdb 4Y1J.pdb 4Y1M.pdb 4Y7N.pdb 4YAZ.pdb 4YCO.pdb 4YCP.pdb 4YHW.pdb 4YOE.pdb 4YVI.pdb 4YYE.pdb 4Z0C.pdb 4Z31.pdb 4Z4D.pdb 4Z7L.pdb 4Z92.pdb 4ZC7.pdb 4ZLD.pdb 4ZLR.pdb 4ZNP.pdb 4ZT0.pdb 5A0T.pdb 5A0V.pdb 5A2Q.pdb 5A8L.pdb 5AH5.pdb 5AJ3.pdb 5AMQ.pdb 5AMR.pdb 5AN9.pdb 5AOR.pdb 5AOX.pdb 5AWH.pdb 5AXM.pdb 5AY3.pdb 5B2Q.pdb 5B43.pdb 5BTM.pdb 5BTP.pdb 5BUD.pdb 5BZ1.pdb 5BZ5.pdb 5BZU.pdb 5BZV.pdb 5C0Y.pdb 5C3E.pdb 5C45.pdb 5C5W.pdb 5C9H.pdb 5CCB.pdb 5CD4.pdb 5CKK.pdb 5CNR.pdb 5CZZ.pdb 5D0A.pdb 5D0B.pdb 5D5L.pdb 5D8H.pdb 5D8T.pdb 5DA6.pdb 5DCV.pdb 5DDO.pdb 5DDP.pdb 5DEA.pdb 5DET.pdb 5DHB.pdb 5DHC.pdb 5DM6.pdb 5DNO.pdb 5DTO.pdb 5DV7.pdb 5E02.pdb 5E17.pdb 5E3H.pdb 5E54.pdb 5E6M.pdb 5EAQ.pdb 5ED1.pdb 5ED2.pdb 5EIM.pdb 5ELH.pdb 5ELK.pdb 5ELR.pdb 5ELS.pdb 5ELT.pdb 5EME.pdb 5EMF.pdb 5EMO.pdb 5EN1.pdb 5EW4.pdb 5EX7.pdb 5F0Q.pdb 5F5F.pdb 5F5H.pdb 5F6C.pdb 5F8H.pdb 5F8N.pdb 5F9F.pdb 5F9R.pdb 5FJ0.pdb 5FJ4.pdb 5FJ8.pdb 5FJC.pdb 5FLM.pdb 5FMZ.pdb 5FN1.pdb 5FW3.pdb 5G2X.pdb 5G4T.pdb 5G4U.pdb 5GAD.pdb 5GAM.pdb 5GAN.pdb 5GAP.pdb 5GJB.pdb 5GMF.pdb 5GMK.pdb 5GUH.pdb 5GXH.pdb 5GXI.pdb 5H1K.pdb 5H1L.pdb 5H3U.pdb 5HAB.pdb 5HBY.pdb 5HL7.pdb 5HNJ.pdb 5HR6.pdb 5HR7.pdb 5I4A.pdb 5I9D.pdb 5I9F.pdb 5I9G.pdb 5I9H.pdb 5ID6.pdb 5IPL.pdb 5IT9.pdb 5IYD.pdb 5J01.pdb 5JAJ.pdb 5JBG.pdb 5JBJ.pdb 5JC7.pdb 5JCF.pdb 5JEA.pdb 5JJI.pdb 5JJK.pdb 5JJL.pdb 5JJU.pdb 5JRC.pdb 5JS1.pdb 5JXS.pdb 5K36.pdb 5K78.pdb 5K8H.pdb 5KI6.pdb 5KK5.pdb 5KL1.pdb 5KL8.pdb 5KLA.pdb 5KPY.pdb 5KTJ.pdb 5KVJ.pdb 5L00.pdb 5L2L.pdb 5LJ3.pdb 5M3H.pdb 5M5Y.pdb 5M73.pdb 5MFX.pdb 5MJV.pdb 5MMI.pdb 5MSF.pdb 5SWE.pdb 5T7B.pdb 5T83.pdb 5TC1.pdb 5TF6.pdb 5TPY.pdb 6MSF.pdb 7MSF.pdb`
RESIDUE_DICT = {'02I': {u'Atom count': u'34 (22 without Hydrogen)',
                        u'Defined at': u'2011-07-27',
                        u'Is modified': u'No',
                        u'Last modified at': u'2012-06-22',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Deoxy ribonucleotide',
                        u'Standard parent': u'Not Assigned',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'DNA LINKING'},
                '12A': {u'Atom count': u'58 (35 without Hydrogen)',
                        u'Defined at': u'2000-08-09',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'A',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                '1CC': {u'Atom count': u'37 (23 without Hydrogen)',
                        u'Defined at': u'2011-11-17',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2012-02-10',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Deoxy ribonucleotide',
                        u'Standard parent': u'DC',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'DNA LINKING'},
                '1DP': {u'Atom count': u'38 (23 without Hydrogen)',
                        u'Defined at': u'2009-07-01',
                        u'Is modified': u'No',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'Not Assigned',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                '1MA': {u'Atom count': u'40 (24 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2015-08-19',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'A',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                '1MG': {u'Atom count': u'41 (25 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'G',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                '1SC': {u'Atom count': u'35 (21 without Hydrogen)',
                        u'Defined at': u'2006-10-19',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'C',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                '23G': {u'Atom count': u'40 (27 without Hydrogen)',
                        u'Defined at': u'2009-09-09',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'G',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA OH 3 prime terminus'},
                '2IA': {u'Atom count': u'36 (23 without Hydrogen)',
                        u'Defined at': u'2011-06-10',
                        u'Is modified': u'No',
                        u'Last modified at': u'2011-08-12',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Deoxy ribonucleotide',
                        u'Standard parent': u'Not Assigned',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'DNA LINKING'},
                '2MA': {u'Atom count': u'40 (24 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'A',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                '2MG': {u'Atom count': u'41 (25 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'G',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                '2MU': {u'Atom count': u'40 (23 without Hydrogen)',
                        u'Defined at': u'2000-08-09',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'U',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                '2PR': {u'Atom count': u'36 (22 without Hydrogen)',
                        u'Defined at': u'2000-07-14',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Deoxy ribonucleotide',
                        u'Standard parent': u'DG',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'DNA LINKING'},
                '2SG': {u'Atom count': u'40 (24 without Hydrogen)',
                        u'Defined at': u'2014-09-22',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2015-09-11',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'G',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                '3DA': {u'Atom count': u'36 (22 without Hydrogen)',
                        u'Defined at': u'2004-02-09',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Deoxy ribonucleotide',
                        u'Standard parent': u'DA',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                '3DR': {u'Atom count': u'23 (12 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Deoxy ribonucleotide',
                        u'Standard parent': u'Not Assigned',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'DNA LINKING'},
                '4OC': {u'Atom count': u'41 (23 without Hydrogen)',
                        u'Defined at': u'2006-08-24',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'C',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                '4SU': {u'Atom count': u'34 (21 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'U',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                '56B': {u'Atom count': u'57 (33 without Hydrogen)',
                        u'Defined at': u'2015-08-03',
                        u'Is modified': u'No',
                        u'Last modified at': u'2016-09-23',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'Not Assigned',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA linking'},
                '5AA': {u'Atom count': u'44 (25 without Hydrogen)',
                        u'Defined at': u'2004-12-29',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Deoxy ribonucleotide',
                        u'Standard parent': u'DA',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                '5BU': {u'Atom count': u'34 (22 without Hydrogen)',
                        u'Defined at': u'2003-11-05',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'U',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                '5CF': {u'Atom count': u'35 (22 without Hydrogen)',
                        u'Defined at': u'2009-10-05',
                        u'Is modified': u'No',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'Not Assigned',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                '5FU': {u'Atom count': u'34 (22 without Hydrogen)',
                        u'Defined at': u'2007-02-02',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'U',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                '5IC': {u'Atom count': u'35 (22 without Hydrogen)',
                        u'Defined at': u'2003-05-13',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'C',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                '5IU': {u'Atom count': u'33 (21 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Deoxy ribonucleotide',
                        u'Standard parent': u'DU',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'DNA LINKING'},
                '5MC': {u'Atom count': u'38 (22 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'C',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                '5MU': {u'Atom count': u'37 (22 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'U',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                '6IA': {u'Atom count': u'52 (28 without Hydrogen)',
                        u'Defined at': u'2001-01-19',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'A',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                '6MZ': {u'Atom count': u'40 (24 without Hydrogen)',
                        u'Defined at': u'2007-03-21',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2014-09-18',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'A',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                '70U': {u'Atom count': u'43 (26 without Hydrogen)',
                        u'Defined at': u'2000-08-08',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'U',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                '7AT': {u'Atom count': u'43 (28 without Hydrogen)',
                        u'Defined at': u'2013-11-22',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2014-06-27',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'A',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                '7MG': {u'Atom count': u'43 (25 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'G',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                '8AZ': {u'Atom count': u'37 (23 without Hydrogen)',
                        u'Defined at': u'2015-10-27',
                        u'Is modified': u'No',
                        u'Last modified at': u'2016-04-08',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'Not Assigned',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA linking'},
                '8OG': {u'Atom count': u'38 (24 without Hydrogen)',
                        u'Defined at': u'2000-10-03',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Deoxy ribonucleotide',
                        u'Standard parent': u'DG',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'DNA LINKING'},
                'A23': {u'Atom count': u'39 (26 without Hydrogen)',
                        u'Defined at': u'1999-10-08',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'A',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                'A2M': {u'Atom count': u'40 (24 without Hydrogen)',
                        u'Defined at': u'2002-07-25',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'A',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                'A2P': {u'Atom count': u'42 (27 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'No',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Bound ligand',
                        u'Standard parent': u'Not Assigned',
                        u'Status': u'Released',
                        u'Type code': u'HETAIN',
                        u'Type description': u'NON-POLYMER'},
                'A5M': {u'Atom count': u'36 (21 without Hydrogen)',
                        u'Defined at': u'2005-03-10',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'C',
                        u'Status': u'Released',
                        u'Type code': u'HETAIN',
                        u'Type description': u'RNA LINKING'},
                'A6A': {u'Atom count': u'40 (24 without Hydrogen)',
                        u'Defined at': u'2010-08-26',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-11-25',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'A',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA linking'},
                'A6C': {u'Atom count': u'38 (22 without Hydrogen)',
                        u'Defined at': u'2010-08-26',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-11-25',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'C',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA linking'},
                'A6G': {u'Atom count': u'41 (25 without Hydrogen)',
                        u'Defined at': u'2010-08-26',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-11-25',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'G',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA linking'},
                'A6U': {u'Atom count': u'37 (22 without Hydrogen)',
                        u'Defined at': u'2010-08-26',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-11-25',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'U',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA linking'},
                'A9Z': {u'Atom count': u'48 (29 without Hydrogen)',
                        u'Defined at': u'2013-01-16',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2013-06-28',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'A',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                'ACA': {u'Atom count': u'22 (9 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'No',
                        u'Last modified at': u'2013-04-17',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Bound ligand',
                        u'Standard parent': u'Not Assigned',
                        u'Status': u'Released',
                        u'Type code': u'HETAIN',
                        u'Type description': u'PEPTIDE LINKING'},
                'ADS': {u'Atom count': u'37 (23 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'No',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Bound ligand',
                        u'Standard parent': u'Not Assigned',
                        u'Status': u'Released',
                        u'Type code': u'HETAIN',
                        u'Type description': u'NON-POLYMER'},
                'AET': {u'Atom count': u'57 (34 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'A',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                'AF2': {u'Atom count': u'36 (23 without Hydrogen)',
                        u'Defined at': u'2010-04-20',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Deoxy ribonucleotide',
                        u'Standard parent': u'DA',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'DNA LINKING'},
                'ALA': {u'Atom count': u'13 (6 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'No',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Amino Acid',
                        u'Standard parent': u'Not Assigned',
                        u'Status': u'Released',
                        u'Type code': u'ATOMP',
                        u'Type description': u'L-PEPTIDE LINKING'},
                'APN': {u'Atom count': u'37 (21 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'No',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Bound ligand',
                        u'Standard parent': u'Not Assigned',
                        u'Status': u'Released',
                        u'Type code': u'HETAIN',
                        u'Type description': u'PEPTIDE-LIKE'},
                'ARG': {u'Atom count': u'27 (12 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'No',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Amino Acid',
                        u'Standard parent': u'Not Assigned',
                        u'Status': u'Released',
                        u'Type code': u'ATOMP',
                        u'Type description': u'L-PEPTIDE LINKING'},
                'ASN': {u'Atom count': u'17 (9 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'No',
                        u'Last modified at': u'2014-11-11',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Amino Acid',
                        u'Standard parent': u'Not Assigned',
                        u'Status': u'Released',
                        u'Type code': u'ATOMP',
                        u'Type description': u'L-PEPTIDE LINKING'},
                'ASP': {u'Atom count': u'16 (9 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'No',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Amino Acid',
                        u'Standard parent': u'Not Assigned',
                        u'Status': u'Released',
                        u'Type code': u'ATOMP',
                        u'Type description': u'L-PEPTIDE LINKING'},
                'ATP': {u'Atom count': u'47 (31 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'No',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Bound ligand',
                        u'Standard parent': u'Not Assigned',
                        u'Status': u'Released',
                        u'Type code': u'HETAIN',
                        u'Type description': u'NON-POLYMER'},
                'AVC': {u'Atom count': u'39 (26 without Hydrogen)',
                        u'Defined at': u'2002-07-25',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'A',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                'BB9': {u'Atom count': u'12 (7 without Hydrogen)',
                        u'Defined at': u'2009-01-15',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Amino Acid',
                        u'Standard parent': u'CYS',
                        u'Status': u'Released',
                        u'Type code': u'ATOMP',
                        u'Type description': u'PEPTIDE LINKING'},
                'BGM': {u'Atom count': u'37 (24 without Hydrogen)',
                        u'Defined at': u'2002-11-21',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Deoxy ribonucleotide',
                        u'Standard parent': u'DG',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'DNA LINKING'},
                'BRU': {u'Atom count': u'33 (21 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Deoxy ribonucleotide',
                        u'Standard parent': u'DU',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'DNA LINKING'},
                'BTN': {u'Atom count': u'32 (16 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'No',
                        u'Last modified at': u'2014-04-29',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Bound ligand',
                        u'Standard parent': u'Not Assigned',
                        u'Status': u'Released',
                        u'Type code': u'HETAIN',
                        u'Type description': u'NON-POLYMER'},
                'CBR': {u'Atom count': u'34 (21 without Hydrogen)',
                        u'Defined at': u'2003-07-16',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Deoxy ribonucleotide',
                        u'Standard parent': u'DC',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'DNA LINKING'},
                'CBV': {u'Atom count': u'35 (22 without Hydrogen)',
                        u'Defined at': u'2006-10-19',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'C',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                'CCC': {u'Atom count': u'37 (24 without Hydrogen)',
                        u'Defined at': u'2000-01-19',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'C',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                'CFL': {u'Atom count': u'34 (21 without Hydrogen)',
                        u'Defined at': u'2006-09-07',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Deoxy ribonucleotide',
                        u'Standard parent': u'DC',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'DNA LINKING'},
                'CFZ': {u'Atom count': u'34 (21 without Hydrogen)',
                        u'Defined at': u'2010-04-13',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Deoxy ribonucleotide',
                        u'Standard parent': u'DC',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'DNA LINKING'},
                'CM0': {u'Atom count': u'41 (26 without Hydrogen)',
                        u'Defined at': u'2007-03-21',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'Not Assigned',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                'CPN': {u'Atom count': u'35 (19 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'No',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Bound ligand',
                        u'Standard parent': u'Not Assigned',
                        u'Status': u'Released',
                        u'Type code': u'HETAIN',
                        u'Type description': u'PEPTIDE-LIKE'},
                'CSX': {u'Atom count': u'15 (8 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Amino Acid',
                        u'Standard parent': u'CYS',
                        u'Status': u'Released',
                        u'Type code': u'ATOMP',
                        u'Type description': u'L-PEPTIDE LINKING'},
                'CVC': {u'Atom count': u'38 (24 without Hydrogen)',
                        u'Defined at': u'2015-10-19',
                        u'Is modified': u'No',
                        u'Last modified at': u'2016-02-19',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'Not Assigned',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA linking'},
                'CYS': {u'Atom count': u'14 (7 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'No',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Amino Acid',
                        u'Standard parent': u'Not Assigned',
                        u'Status': u'Released',
                        u'Type code': u'ATOMP',
                        u'Type description': u'L-PEPTIDE LINKING'},
                'DAL': {u'Atom count': u'13 (6 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Amino Acid',
                        u'Standard parent': u'ALA',
                        u'Status': u'Released',
                        u'Type code': u'ATOMP',
                        u'Type description': u'D-PEPTIDE LINKING'},
                'DBU': {u'Atom count': u'14 (7 without Hydrogen)',
                        u'Defined at': u'2004-03-16',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Amino Acid',
                        u'Standard parent': u'THR',
                        u'Status': u'Released',
                        u'Type code': u'ATOMP',
                        u'Type description': u'PEPTIDE LINKING'},
                'DCY': {u'Atom count': u'14 (7 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Amino Acid',
                        u'Standard parent': u'CYS',
                        u'Status': u'Released',
                        u'Type code': u'ATOMP',
                        u'Type description': u'D-PEPTIDE LINKING'},
                'DHA': {u'Atom count': u'11 (6 without Hydrogen)',
                        u'Defined at': u'1999-11-22',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Amino Acid',
                        u'Standard parent': u'SER',
                        u'Status': u'Released',
                        u'Type code': u'ATOMP',
                        u'Type description': u'PEPTIDE LINKING'},
                'DOC': {u'Atom count': u'33 (19 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Deoxy ribonucleotide',
                        u'Standard parent': u'DC',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'DNA LINKING'},
                'FGA': {u'Atom count': u'19 (10 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Amino Acid',
                        u'Standard parent': u'GLU',
                        u'Status': u'Released',
                        u'Type code': u'ATOMP',
                        u'Type description': u'D-gamma-peptide, C-delta linking'},
                'FHU': {u'Atom count': u'37 (23 without Hydrogen)',
                        u'Defined at': u'2001-11-02',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'U',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                'FMU': {u'Atom count': u'39 (23 without Hydrogen)',
                        u'Defined at': u'2005-01-06',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'Not Assigned',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                'G46': {u'Atom count': u'38 (24 without Hydrogen)',
                        u'Defined at': u'1998-01-07',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2015-02-12',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'G',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                'G7M': {u'Atom count': u'42 (25 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'G',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                'GDO': {u'Atom count': u'37 (23 without Hydrogen)',
                        u'Defined at': u'2012-04-11',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2012-04-13',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'G',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                'GF2': {u'Atom count': u'37 (24 without Hydrogen)',
                        u'Defined at': u'2010-04-20',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Deoxy ribonucleotide',
                        u'Standard parent': u'DG',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'DNA linking'},
                'GLN': {u'Atom count': u'20 (10 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'No',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Amino Acid',
                        u'Standard parent': u'Not Assigned',
                        u'Status': u'Released',
                        u'Type code': u'ATOMP',
                        u'Type description': u'L-PEPTIDE LINKING'},
                'GLU': {u'Atom count': u'19 (10 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'No',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Amino Acid',
                        u'Standard parent': u'Not Assigned',
                        u'Status': u'Released',
                        u'Type code': u'ATOMP',
                        u'Type description': u'L-PEPTIDE LINKING'},
                'GLY': {u'Atom count': u'10 (5 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'No',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Amino Acid',
                        u'Standard parent': u'Not Assigned',
                        u'Status': u'Released',
                        u'Type code': u'ATOMP',
                        u'Type description': u'PEPTIDE LINKING'},
                'GPN': {u'Atom count': u'38 (22 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'No',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Bound ligand',
                        u'Standard parent': u'Not Assigned',
                        u'Status': u'Released',
                        u'Type code': u'HETAIN',
                        u'Type description': u'PEPTIDE-LIKE'},
                'GRB': {u'Atom count': u'38 (25 without Hydrogen)',
                        u'Defined at': u'2011-03-15',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'G',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                'H2U': {u'Atom count': u'36 (21 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'U',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                'HFA': {u'Atom count': u'22 (12 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Amino Acid',
                        u'Standard parent': u'UNK',
                        u'Status': u'Released',
                        u'Type code': u'ATOMP',
                        u'Type description': u'L-PEPTIDE LINKING'},
                'HIS': {u'Atom count': u'21 (11 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'No',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Amino Acid',
                        u'Standard parent': u'Not Assigned',
                        u'Status': u'Released',
                        u'Type code': u'ATOMP',
                        u'Type description': u'L-PEPTIDE LINKING'},
                'HYP': {u'Atom count': u'18 (9 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Amino Acid',
                        u'Standard parent': u'PRO',
                        u'Status': u'Released',
                        u'Type code': u'ATOMP',
                        u'Type description': u'L-PEPTIDE LINKING'},
                'ILE': {u'Atom count': u'22 (9 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'No',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Amino Acid',
                        u'Standard parent': u'Not Assigned',
                        u'Status': u'Released',
                        u'Type code': u'ATOMP',
                        u'Type description': u'L-PEPTIDE LINKING'},
                'LCA': {u'Atom count': u'38 (24 without Hydrogen)',
                        u'Defined at': u'2002-06-27',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'A',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                'LCC': {u'Atom count': u'39 (23 without Hydrogen)',
                        u'Defined at': u'2002-06-27',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'Not Assigned',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                'LCG': {u'Atom count': u'39 (25 without Hydrogen)',
                        u'Defined at': u'2002-06-27',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Deoxy ribonucleotide',
                        u'Standard parent': u'DG',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                'LEU': {u'Atom count': u'22 (9 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'No',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Amino Acid',
                        u'Standard parent': u'Not Assigned',
                        u'Status': u'Released',
                        u'Type code': u'ATOMP',
                        u'Type description': u'L-PEPTIDE LINKING'},
                'LYS': {u'Atom count': u'25 (10 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'No',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Amino Acid',
                        u'Standard parent': u'Not Assigned',
                        u'Status': u'Released',
                        u'Type code': u'ATOMP',
                        u'Type description': u'L-PEPTIDE LINKING'},
                'M2G': {u'Atom count': u'44 (26 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'G',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                'MA6': {u'Atom count': u'43 (25 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'A',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                'MET': {u'Atom count': u'20 (9 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'No',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Amino Acid',
                        u'Standard parent': u'Not Assigned',
                        u'Status': u'Released',
                        u'Type code': u'ATOMP',
                        u'Type description': u'L-PEPTIDE LINKING'},
                'MH6': {u'Atom count': u'12 (7 without Hydrogen)',
                        u'Defined at': u'2008-03-11',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-11-17',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Amino Acid',
                        u'Standard parent': u'SER',
                        u'Status': u'Released',
                        u'Type code': u'ATOMP',
                        u'Type description': u'PEPTIDE LINKING'},
                'MIA': {u'Atom count': u'56 (30 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'A',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                'MLZ': {u'Atom count': u'27 (11 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Amino Acid',
                        u'Standard parent': u'LYS',
                        u'Status': u'Released',
                        u'Type code': u'ATOMP',
                        u'Type description': u'L-PEPTIDE LINKING'},
                'MSE': {u'Atom count': u'20 (9 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Amino Acid',
                        u'Standard parent': u'MET',
                        u'Status': u'Released',
                        u'Type code': u'ATOMP',
                        u'Type description': u'L-PEPTIDE LINKING'},
                'MTU': {u'Atom count': u'37 (23 without Hydrogen)',
                        u'Defined at': u'2004-04-09',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'A',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                'N6G': {u'Atom count': u'39 (24 without Hydrogen)',
                        u'Defined at': u'2005-10-24',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'G',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                'NCU': {u'Atom count': u'44 (25 without Hydrogen)',
                        u'Defined at': u'2014-08-05',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2015-08-14',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Deoxy ribonucleotide',
                        u'Standard parent': u'DC',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'DNA linking'},
                'NF2': {u'Atom count': u'37 (22 without Hydrogen)',
                        u'Defined at': u'2006-03-07',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'Not Assigned',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                'NH2': {u'Atom count': u'3 (1 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'No',
                        u'Last modified at': u'2008-10-14',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Bound ligand',
                        u'Standard parent': u'Not Assigned',
                        u'Status': u'Released',
                        u'Type code': u'HETAIN',
                        u'Type description': u'NON-POLYMER'},
                'NTT': {u'Atom count': u'43 (25 without Hydrogen)',
                        u'Defined at': u'2014-08-05',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2015-08-14',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Deoxy ribonucleotide',
                        u'Standard parent': u'DT',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'DNA linking'},
                'O2C': {u'Atom count': u'34 (20 without Hydrogen)',
                        u'Defined at': u'2005-10-31',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'Not Assigned',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                'OMC': {u'Atom count': u'38 (22 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'C',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                'OMG': {u'Atom count': u'41 (25 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'G',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                'OMU': {u'Atom count': u'37 (22 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'U',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                'P5P': {u'Atom count': u'35 (22 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'A',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                'PGN': {u'Atom count': u'42 (27 without Hydrogen)',
                        u'Defined at': u'2001-07-02',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Deoxy ribonucleotide',
                        u'Standard parent': u'DG',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'DNA LINKING'},
                'PGP': {u'Atom count': u'43 (28 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'G',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                'PHE': {u'Atom count': u'23 (12 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'No',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Amino Acid',
                        u'Standard parent': u'Not Assigned',
                        u'Status': u'Released',
                        u'Type code': u'ATOMP',
                        u'Type description': u'L-PEPTIDE LINKING'},
                'PO2': {u'Atom count': u'3 (3 without Hydrogen)',
                        u'Defined at': u'2001-05-14',
                        u'Is modified': u'No',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Bound ligand',
                        u'Standard parent': u'Not Assigned',
                        u'Status': u'Released',
                        u'Type code': u'HETAIN',
                        u'Type description': u'NON-POLYMER'},
                'PO4': {u'Atom count': u'5 (5 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'No',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Bound ligand',
                        u'Standard parent': u'Not Assigned',
                        u'Status': u'Released',
                        u'Type code': u'HETAI',
                        u'Type description': u'NON-POLYMER'},
                'PPU': {u'Atom count': u'68 (38 without Hydrogen)',
                        u'Defined at': u'2000-07-31',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'A',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                'PRO': {u'Atom count': u'17 (8 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'No',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Amino Acid',
                        u'Standard parent': u'Not Assigned',
                        u'Status': u'Released',
                        u'Type code': u'ATOMP',
                        u'Type description': u'L-PEPTIDE LINKING'},
                'PSU': {u'Atom count': u'34 (21 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'U',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                'PYY': {u'Atom count': u'34 (19 without Hydrogen)',
                        u'Defined at': u'2000-10-27',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'Not Assigned',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                'QUO': {u'Atom count': u'59 (33 without Hydrogen)',
                        u'Defined at': u'1999-07-20',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'G',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                'RIA': {u'Atom count': u'59 (36 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'A',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                'RPC': {u'Atom count': u'40 (25 without Hydrogen)',
                        u'Defined at': u'2012-12-11',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2013-04-19',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'C',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                'RSQ': {u'Atom count': u'37 (23 without Hydrogen)',
                        u'Defined at': u'2010-01-25',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2016-02-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'C',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                'RUS': {u'Atom count': u'34 (21 without Hydrogen)',
                        u'Defined at': u'2011-06-02',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-24',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'U',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA linking'},
                'S9L': {u'Atom count': u'29 (14 without Hydrogen)',
                        u'Defined at': u'2006-11-16',
                        u'Is modified': u'No',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Bound ligand',
                        u'Standard parent': u'Not Assigned',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'NON-POLYMER'},
                'SEP': {u'Atom count': u'19 (11 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Amino Acid',
                        u'Standard parent': u'SER',
                        u'Status': u'Released',
                        u'Type code': u'ATOMP',
                        u'Type description': u'L-PEPTIDE LINKING'},
                'SER': {u'Atom count': u'14 (7 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'No',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Amino Acid',
                        u'Standard parent': u'Not Assigned',
                        u'Status': u'Released',
                        u'Type code': u'ATOMP',
                        u'Type description': u'L-PEPTIDE LINKING'},
                'SMC': {u'Atom count': u'17 (8 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Amino Acid',
                        u'Standard parent': u'CYS',
                        u'Status': u'Released',
                        u'Type code': u'ATOMP',
                        u'Type description': u'L-PEPTIDE LINKING'},
                'SUR': {u'Atom count': u'34 (21 without Hydrogen)',
                        u'Defined at': u'2000-11-21',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'U',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                'T2T': {u'Atom count': u'80 (44 without Hydrogen)',
                        u'Defined at': u'2006-05-12',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'Not Assigned',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                'T6A': {u'Atom count': u'54 (33 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'A',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                'THR': {u'Atom count': u'17 (8 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'No',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Amino Acid',
                        u'Standard parent': u'Not Assigned',
                        u'Status': u'Released',
                        u'Type code': u'ATOMP',
                        u'Type description': u'L-PEPTIDE LINKING'},
                'TLN': {u'Atom count': u'38 (23 without Hydrogen)',
                        u'Defined at': u'2001-01-04',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Deoxy ribonucleotide',
                        u'Standard parent': u'DU',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                'TM2': {u'Atom count': u'49 (29 without Hydrogen)',
                        u'Defined at': u'2008-03-14',
                        u'Is modified': u'No',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Bound ligand',
                        u'Standard parent': u'Not Assigned',
                        u'Status': u'Released',
                        u'Type code': u'',
                        u'Type description': u'non-polymer'},
                'TPN': {u'Atom count': u'37 (20 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'No',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Bound ligand',
                        u'Standard parent': u'Not Assigned',
                        u'Status': u'Released',
                        u'Type code': u'HETAIN',
                        u'Type description': u'PEPTIDE-LIKE'},
                'TPO': {u'Atom count': u'22 (12 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Amino Acid',
                        u'Standard parent': u'THR',
                        u'Status': u'Released',
                        u'Type code': u'ATOMP',
                        u'Type description': u'L-PEPTIDE LINKING'},
                'TRP': {u'Atom count': u'27 (15 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'No',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Amino Acid',
                        u'Standard parent': u'Not Assigned',
                        u'Status': u'Released',
                        u'Type code': u'ATOMP',
                        u'Type description': u'L-PEPTIDE LINKING'},
                'TRX': {u'Atom count': u'28 (16 without Hydrogen)',
                        u'Defined at': u'2001-10-29',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-08-31',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Amino Acid',
                        u'Standard parent': u'TRP',
                        u'Status': u'Released',
                        u'Type code': u'ATOMP',
                        u'Type description': u'L-PEPTIDE LINKING'},
                'TS9': {u'Atom count': u'24 (11 without Hydrogen)',
                        u'Defined at': u'2008-03-11',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Amino Acid',
                        u'Standard parent': u'ILE',
                        u'Status': u'Released',
                        u'Type code': u'ATOMP',
                        u'Type description': u'L-PEPTIDE LINKING'},
                'TSE': {u'Atom count': u'13 (8 without Hydrogen)',
                        u'Defined at': u'2005-01-14',
                        u'Is modified': u'No',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Bound ligand',
                        u'Standard parent': u'Not Assigned',
                        u'Status': u'Released',
                        u'Type code': u'HETAIN',
                        u'Type description': u'NON-POLYMER'},
                'TYR': {u'Atom count': u'24 (13 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'No',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Amino Acid',
                        u'Standard parent': u'Not Assigned',
                        u'Status': u'Released',
                        u'Type code': u'ATOMP',
                        u'Type description': u'L-PEPTIDE LINKING'},
                'U34': {u'Atom count': u'37 (22 without Hydrogen)',
                        u'Defined at': u'2000-04-17',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'U',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                'U37': {u'Atom count': u'34 (21 without Hydrogen)',
                        u'Defined at': u'1998-01-07',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'U',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                'U5M': {u'Atom count': u'36 (22 without Hydrogen)',
                        u'Defined at': u'2015-08-18',
                        u'Is modified': u'No',
                        u'Last modified at': u'2016-06-24',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'Not Assigned',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA linking'},
                'UFT': {u'Atom count': u'33 (21 without Hydrogen)',
                        u'Defined at': u'2008-07-07',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Deoxy ribonucleotide',
                        u'Standard parent': u'DU',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'DNA LINKING'},
                'UNK': {u'Atom count': u'16 (7 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'No',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Amino Acid',
                        u'Standard parent': u'Not Assigned',
                        u'Status': u'Released',
                        u'Type code': u'ATOMP',
                        u'Type description': u'L-PEPTIDE LINKING'},
                'UR3': {u'Atom count': u'37 (22 without Hydrogen)',
                        u'Defined at': u'2004-03-17',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-12-06',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'U',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                'URU': {u'Atom count': u'66 (40 without Hydrogen)',
                        u'Defined at': u'2014-01-07',
                        u'Is modified': u'No',
                        u'Last modified at': u'2014-07-03',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'Not Assigned',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                'US5': {u'Atom count': u'34 (21 without Hydrogen)',
                        u'Defined at': u'2009-07-17',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'U',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                'VAL': {u'Atom count': u'19 (8 without Hydrogen)',
                        u'Defined at': u'1999-07-08',
                        u'Is modified': u'No',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Amino Acid',
                        u'Standard parent': u'Not Assigned',
                        u'Status': u'Released',
                        u'Type code': u'ATOMP',
                        u'Type description': u'L-PEPTIDE LINKING'},
                'XAR': {u'Atom count': u'39 (23 without Hydrogen)',
                        u'Defined at': u'2007-04-18',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Deoxy ribonucleotide',
                        u'Standard parent': u'Not Assigned',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'DNA LINKING'},
                'XCR': {u'Atom count': u'37 (21 without Hydrogen)',
                        u'Defined at': u'2009-11-20',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Deoxy ribonucleotide',
                        u'Standard parent': u'DC',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'DNA LINKING'},
                'XGR': {u'Atom count': u'40 (24 without Hydrogen)',
                        u'Defined at': u'2009-11-20',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Deoxy ribonucleotide',
                        u'Standard parent': u'DG',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'DNA LINKING'},
                'XTR': {u'Atom count': u'39 (22 without Hydrogen)',
                        u'Defined at': u'2009-01-05',
                        u'Is modified': u'Yes',
                        u'Last modified at': u'2011-06-04',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Deoxy ribonucleotide',
                        u'Standard parent': u'DT',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'DNA linking'},
                'Y5P': {u'Atom count': u'34 (19 without Hydrogen)',
                        u'Defined at': u'2014-09-25',
                        u'Is modified': u'No',
                        u'Last modified at': u'2014-10-03',
                        u'Obsoleted': u'Not Assigned',
                        u'Polymer type': u'Ribonucleotide',
                        u'Standard parent': u'Not Assigned',
                        u'Status': u'Released',
                        u'Type code': u'ATOMN',
                        u'Type description': u'RNA LINKING'},
                'MG': None,
                'K': None,
                'NA': None,
                'CL': None
                }
